// Contains a basic query for fetching ads.
// More complex queries with filtering and pagination will be added later.

export const ADS_QUERY = `
  query Ads($limit: Int, $page: Int, $sort: String, $where: JSON) { # Added where
    Ads(limit: $limit, page: $page, sort: $sort, where: $where) { # Added where
      docs {
        id
        slug
        title
        price
        currency
        location
        adType
        description # Consider if full description is needed for list view, maybe a summary
        status
        author {
          id
          name
        }
        categories {
          id
          title
        }
        # Add meta fields if needed for links, like slug from meta.image
        # meta {
        #   title
        #   description
        #   image {
        #     url
        #   }
        # }
      }
      totalDocs
      totalPages
      page
      limit
      hasNextPage
      hasPrevPage
    }
  }
`

// Query for a single Ad by slug
export const AD_QUERY_BY_SLUG = `
  query AdBySlug($slug: String) { # Renamed for clarity
    Ads(where: { slug: { equals: $slug } }) {
      docs {
        id
        title
        description
        price
        currency
        location
        adType
        slug
        status
        author {
          id
          name
          email # For contact, if allowed by user settings
        }
        categories {
          id
          title
        }
        contactName
        contactPhone
        contactEmail
        # Add more fields as needed, e.g., images
        # adImages {
        #   id
        #   url
        #   alt
        # }
        # meta {
        #   title
        #   description
        #   image {
        #     url
        #   }
        # }
      }
    }
  }
`

// Query for a single Ad by ID (useful for editing)
export const AD_QUERY_BY_ID = `
  query AdById($id: String!) {
    Ads(where: { id: { equals: $id } }) { # Query by ID
      docs {
        id
        title
        description # This will be JSON if RichText, String if Textarea
        price
        currency
        location
        adType
        slug
        status
        author {
          id
          name
        }
        categories {
          id
          title
        }
        contactName
        contactPhone
        contactEmail
      }
    }
  }
`


export const CREATE_AD_MUTATION = `
  mutation CreateAd(
    $title: String!,
    $description: JSON!, # Assuming description is RichText (JSON) or String for Payload
    $price: Float!,
    $currency: String!,
    $location: String!,
    $adType: String!,
    $categories: [String], # Array of Category IDs
    $contactName: String,
    $contactPhone: String,
    $contactEmail: String,
    $status: String # e.g., "draft" or "published"
    # author will be set by the backend hook based on logged-in user
  ) {
    createAd(data: {
      title: $title,
      description: $description,
      price: $price,
      currency: $currency,
      location: $location,
      adType: $adType,
      categories: $categories,
      contactName: $contactName,
      contactPhone: $contactPhone,
      contactEmail: $contactEmail,
      status: $status
      # slug will be auto-generated by backend hook
    }) {
      id
      slug
      title
      status
    }
  }
`

export const UPDATE_AD_MUTATION = `
  mutation UpdateAd(
    $id: String!, # ID of the ad to update
    $title: String,
    $description: JSON, # Assuming description is RichText (JSON) or String
    $price: Float,
    $currency: String,
    $location: String,
    $adType: String,
    $categories: [String],
    $contactName: String,
    $contactPhone: String,
    $contactEmail: String,
    $status: String
  ) {
    updateAd(
      id: $id,
      data: {
        title: $title,
        description: $description,
        price: $price,
        currency: $currency,
        location: $location,
        adType: $adType,
        categories: $categories,
        contactName: $contactName,
        contactPhone: $contactPhone,
        contactEmail: $contactEmail,
        status: $status
      }
    ) {
      id
      slug
      title
      status
    }
  }
`

export const DELETE_AD_MUTATION = `
  mutation DeleteAd($id: String!) {
    deleteAd(id: $id) {
      id # Or any field to confirm deletion
    }
  }
`
